valuesFilePath: ./values.yml

resources:
  - name: jira_transition_task_git_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: ssh
  - name: jira_comment_task_git_repo
    type: GitRepo
    configuration:
      path: deepikasl/jira-comment
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: ssh
      
pipelines:
  - name: jira_transition_task_publish_pipeline
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          TASK_NAME: jira-transition
          TASK_VERSION: 0.0.${run_number}
          TASK_REPOSITORY: pipelines-tasks-local
          RESOLVE_REPO: npm-virtual
          JIRA_INT: deepikajira
    steps:
      - name: test_published_jira_transition_task
        type: Bash
        configuration:
          inputResources:
            - name: jira_transition_task_git_repo
              trigger: false
            - name: jira_comment_task_git_repo
              trigger: false
          integrations:
            - name: {{ .Values.artIntegration }}
            - name: {{ .Values.jiraIntegration }}
        execution:
          onExecute:
            - echo "here"
          onSuccess:
            - pushd $res_jira_comment_task_git_repo_resourcePath
            - jf npmc --repo-resolve $RESOLVE_REPO
            - npm install
            - npm run dist
            - popd
            # Run task
            - task: $res_jira_comment_task_git_repo_resourcePath
              input:
                issue_key: "TAS-1"
                jira_integration_name: deepikajira
                comment: "Step executed successfully: $step_url"
            - pushd $res_jira_transition_task_git_repo_resourcePath
            - jf npmc --repo-resolve $RESOLVE_REPO
            - npm install
            - npm run dist
            - popd
            # Run task
            - task: $res_jira_transition_task_git_repo_resourcePath
              input:
                issue_key: "TAS-1"
                jira_integration_name: deepikajira
                transition_name: "Done"
